require(data.table)
#rm(list = ls())
#set.seed(1000)
source("scripts/functions.R")
source("scripts/parameter_and_inits.R")
source("scripts/input0.R")
make_parms(input0, secon_subpop)
make_troph_net(input0, Species)
source("scripts/initialization.R")
source("scripts/run.R") # Encounters3 is active (network)
##pdf()
#source("scripts/ploscri.R")
#source("scripts/plot.R")
#dev.off()

#a plot(0, 0, ylim = c(0, max(Spuno1$biomass)), xlim = range(Time))
#a abline(h = c(1, 2) * Spuno1$basemass, lty = 2, col = c(2, 3))
#a by(Spuno1$biomass, Spuno1$id, points, type = "l")
#a plot(0, 0, ylim = c(0, max(Spuno2$biomass)), xlim = range(Time))
#a by(Spuno2$biomass, Spuno2$id, points, type = "l")
#a abline(h = c(1, 2) * Spuno2$basemass, lty = 2, col = c(2, 3))
#a plot(0, 0, ylim = c(0, max(Spuno3$biomass)), xlim = range(Time))
#a by(Spuno3$biomass, Spuno3$id, points, type = "l")
#a abline(h = c(1, 2) * Spuno3$basemass, lty = 2, col = c(2, 3))
#a plot(0, 0, ylim = c(0, max(Spuno4$biomass)), xlim = range(Time))
#a by(Spuno4$biomass, Spuno4$id, points, type = "l")
#a abline(h = c(1, 2) * Spuno4$basemass, lty = 2, col = c(2, 3))
